version: "3.10"

volumes:
  sensor_db_data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - sensor_db_data:/data
    restart: always  # Ensures backend restarts if it crashes

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always  # Ensures dashboard restarts if it crashes

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - backend
    restart: always  # Ensures producer restarts if it crashes

